import './index.css'

export { default as CoreInputTemplate } from '@/_InputTemplate/index.vue'
export { default as CoreButton } from '@/Button/index.vue'
export { default as CoreContentLoader } from '@/ContentLoader/index.vue'
export { IconModules } from '@/Icon/iconsLoader.js'
export { default as CoreIcon } from '@/Icon/index.vue'
export { default as CoreInput } from '@/Input/index.vue'
export { default as CoreInputCheckbox } from '@/InputCheckbox/index.vue'
export { default as CoreInputCheckboxGroup } from '@/InputCheckboxGroup/index.vue'
export { default as CoreInputMultiselect } from '@/InputMultiselect/index.vue'
export { default as CoreInputRadio } from '@/InputRadio/index.vue'
export { default as CoreInputRadioGroup } from '@/InputRadioGroup/index.vue'
export { default as CoreInputSwitch } from '@/InputSwitch/index.vue'
export { default as CoreInputTextarea } from '@/InputTextarea/index.vue'
export { default as CoreModal } from '@/Modal/index.vue'
export { default as CoreNotifications } from '@/Notifications/index.vue'
export { createNotification } from '@/Notifications/handler.js'
